[[redirects]]
  from = "/vivaan"
  to = "/vivaan/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/vivaan/"
  to = "/vivaan/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "/blog/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog/"
  to = "/blog/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/adatewithnumbers"
  to = "/adatewithnumbers/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/adatewithnumbers/"
  to = "/adatewithnumbers/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/mathsgrade7"
  to = "/mathsgrade7/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/mathsgrade7/"
  to = "/mathsgrade7/index.html"
  status = 200
  force = true
